// BSD מחשבים – בניית כרטיסי המוצרים וסינון. קישורי וואטסאפ/מייל: contact.js

function el(tag, cls, text) {
  const e = document.createElement(tag);
  if (cls) e.className = cls;
  if (text != null) e.textContent = text;
  return e;
}

// lower-case, drop direction marks, quotes and punctuation so "i7 14700" finds "i7-14700HX"
function norm(t) {
  return t.toLowerCase().replace(/[\u200e\u200f"'״׳`]/g, "").replace(/[-·,:()/+]/g, " ").replace(/\s+/g, " ").trim();
}

function card(p) {
  const c = el("article", "card" + (p.deal ? " card-deal" : ""));
  c.dataset.cat = [p.cat, ...(p.also || [])].join(" ");
  const catNames = [p.cat, ...(p.also || [])].map(id => CATEGORIES.find(x => x.id === id).name);
  c.dataset.search = norm([p.sku, p.brand, p.name, p.tagline, p.deal || "", ...p.specs, ...catNames].join(" "));

  const media = el(p.page ? "a" : "div", "card-media");
  if (p.page) media.href = p.page;
  const img = el("img");
  img.src = p.img;
  img.alt = p.name;
  img.loading = "lazy";
  img.width = 510;
  img.height = 510;
  media.append(img, el("span", "badge-cat", CATEGORIES.find(x => x.id === p.cat).name));
  if (p.deal) media.append(el("span", "badge-deal", p.deal));
  c.append(media);

  const body = el("div", "card-body");
  const meta = el("div", "card-meta");
  meta.append(el("span", "brand", p.brand), el("span", "sku", "מק\"ט: " + p.sku));
  const title = el("h3", "card-title");
  // names are LTR (Latin model names); mixed Hebrew names read better RTL
  if (/[\u0590-\u05FF]/.test(p.name)) title.style.direction = "rtl";
  if (p.page) { const t = el("a", null, p.name); t.href = p.page; title.append(t); }
  else title.textContent = p.name;
  body.append(meta, title, el("p", "tagline", p.tagline));

  const specs = el("ul", "specs");
  p.specs.forEach(s => specs.append(el("li", null, s)));
  body.append(specs);

  // computers come installed + free shipping; printers and monitors don't carry those chips
  const noun = { printers: "מדפסת", monitors: "מסך" }[p.cat] || "מחשב";
  if (noun === "מחשב") {
    const incl = el("div", "included");
    incl.append(el("span", "chip chip-ok", "✓ כולל התקנות מלאות"), el("span", "chip chip-ship", "🚚 משלוח חינם"));
    body.append(incl);
  }

  // מציאון: compare with the lowest new-model price on Zap
  if (p.zap) {
    const saving = parseInt(p.zap.price.replace(/,/g, ""), 10) - parseInt(p.price.replace(/,/g, ""), 10);
    const z = el("div", "zap-line");
    z.append(el("span", null, "בזאפ (חדש): ₪" + p.zap.price));
    if (saving > 0) z.append(el("b", null, "חוסכים ₪" + saving.toLocaleString("en-US")));
    z.title = p.zap.label;
    body.append(z);
  }

  // regular products on sale: strike the market price and show the saving
  if (p.was) {
    const saving = parseInt(p.was.replace(/,/g, ""), 10) - parseInt(p.price.replace(/,/g, ""), 10);
    const w = el("div", "zap-line");
    w.append(el("span", null, "מחיר שוק: ₪" + p.was));
    if (saving > 0) w.append(el("b", null, "חוסכים ₪" + saving.toLocaleString("en-US")));
    body.append(w);
  }
  if (p.stockLow) {
    const st = el("div", "stock-low stock-low-card");
    st.append(el("span", "stock-dot"), document.createTextNode("יחידות בודדות במלאי"));
    body.append(st);
  }

  const foot = el("div", "card-foot");
  const priceRow = el("div", "price-row");
  priceRow.append(el("div", "price" + (p.deal ? " price-deal" : ""), p.price ? "₪" + p.price : "מחיר לפי פנייה"));
  if (p.page) { const more = el("a", "more-link", "לכל הפרטים ←"); more.href = p.page; priceRow.append(more); }
  foot.append(priceRow);
  const msg = `שלום, אני מתעניין/ת ב${noun} ${p.name} (מק"ט ${p.sku}). אשמח לפרטים ומחיר.`;
  const btns = el("div", "order-btns");
  const wa = el("a", "btn btn-wa", "להזמנה בוואטסאפ");
  wa.href = waLink(msg);
  wa.target = "_blank";
  wa.rel = "noopener";
  const mail = el("a", "btn btn-mail");
  mail.href = mailLink(`הזמנת ${noun}: ${p.name} (מק"ט ${p.sku})`, msg);
  mail.innerHTML = MAIL_ICON;
  mail.append(el("span", null, "להזמנה במייל"));
  btns.append(wa, mail);
  foot.append(btns);
  body.append(foot);

  c.append(body);
  return c;
}

// קישור ישיר לקטגוריה: bsd-comp.com/#arch, ‏bsd-comp.com/#recommended וכו'
const SITE_URL = "https://bsd-comp.com/";

// soldOut: true hides a product from the catalog (temporarily out of stock)
// DEALS (deals.js) = the מציאון category, generated by the update-deals skill
// priced products always come first in every view (stable sort keeps the list order within each group)
const SHOWN = PRODUCTS.concat(typeof DEALS !== "undefined" ? DEALS : []).filter(p => !p.soldOut)
  .sort((a, b) => (b.price ? 1 : 0) - (a.price ? 1 : 0));

function render() {
  const grid = document.getElementById("grid");
  SHOWN.forEach(p => grid.append(card(p)));

  const filters = document.getElementById("filters");

  // search box: matches model, SKU, processor, specs and category (all words must match)
  const search = el("div", "search");
  const input = el("input", "search-input");
  input.type = "search";
  input.placeholder = "חיפוש: דגם, מעבד, מק\"ט או מפרט";
  input.setAttribute("aria-label", "חיפוש מחשב");
  input.autocomplete = "off";
  const clear = el("button", "search-clear", "✕");
  clear.type = "button";
  clear.setAttribute("aria-label", "ניקוי החיפוש");
  clear.hidden = true;
  search.append(el("span", "search-ic", "🔍"), input, clear);
  filters.before(search);
  const empty = el("p", "no-results");
  empty.hidden = true;
  grid.after(empty);
  let current = { id: "all" };

  function apply() {
    const words = norm(input.value).split(" ").filter(Boolean);
    let shown = 0;
    grid.querySelectorAll(".card").forEach(c => {
      const inCat = current.id === "all" || c.dataset.cat.split(" ").includes(current.id);
      const hit = words.every(w => c.dataset.search.includes(w));
      c.hidden = !(inCat && hit);
      if (!c.hidden) shown++;
    });
    clear.hidden = !input.value;
    empty.hidden = shown > 0;
    if (!shown) {
      empty.replaceChildren(`לא נמצאו מחשבים עבור "${input.value.trim()}"${current.id !== "all" ? " בקטגוריה " + current.name : ""}. `);
      const ask = el("a", null, "שאלו אותנו בוואטסאפ");
      ask.href = waLink(`שלום, אני מחפש/ת מחשב: ${input.value.trim()}`);
      ask.target = "_blank";
      ask.rel = "noopener";
      empty.append(ask);
    }
  }
  input.addEventListener("input", apply);
  clear.addEventListener("click", () => { input.value = ""; apply(); input.focus(); });

  const share = el("div", "cat-share");
  share.hidden = true;
  filters.after(share);

  const all = [{ id: "all", name: "הכל" }, ...CATEGORIES];
  const buttons = {};

  function select(cat, updateUrl) {
    filters.querySelectorAll(".filter").forEach(f => { f.classList.remove("active"); f.setAttribute("aria-selected", "false"); });
    const b = buttons[cat.id];
    b.classList.add("active");
    b.setAttribute("aria-selected", "true");
    current = cat;
    apply();
    if (updateUrl) history.replaceState(null, "", cat.id === "all" ? "#laptops" : "#" + cat.id);
    renderShare(cat);
  }

  function renderShare(cat) {
    share.replaceChildren();
    share.hidden = cat.id === "all";
    if (share.hidden) return;
    const url = SITE_URL + "#" + cat.id;
    const label = el("span", "cat-share-label", "קישור ישיר לקטגוריה:");
    const link = el("a", "cat-share-url", url);
    link.href = url;
    link.dir = "ltr";
    const copy = el("button", "cat-share-btn", "📋 העתקה");
    copy.type = "button";
    copy.addEventListener("click", async () => {
      try { await navigator.clipboard.writeText(url); }
      catch { const t = el("textarea"); t.value = url; document.body.append(t); t.select(); document.execCommand("copy"); t.remove(); }
      copy.textContent = "✓ הועתק";
      setTimeout(() => { copy.textContent = "📋 העתקה"; }, 1800);
    });
    const wa = el("a", "cat-share-btn cat-share-wa", "שליחה בוואטסאפ");
    wa.href = "https://wa.me/?text=" + encodeURIComponent(`${cat.name} – BSD מחשבים\n${url}`);
    wa.target = "_blank";
    wa.rel = "noopener";
    share.append(label, link, copy, wa);
  }

  all.forEach((cat, i) => {
    const b = el("button", "filter" + (i === 0 ? " active" : ""), cat.name);
    b.type = "button";
    b.setAttribute("role", "tab");
    b.setAttribute("aria-selected", i === 0 ? "true" : "false");
    const count = cat.id === "all" ? SHOWN.length : SHOWN.filter(p => p.cat === cat.id || (p.also || []).includes(cat.id)).length;
    b.append(el("span", "count", String(count)));
    b.addEventListener("click", () => select(cat, true));
    buttons[cat.id] = b;
    filters.append(b);
  });

  // opening the site with #<category> selects it and scrolls to the catalog
  function fromHash() {
    const cat = CATEGORIES.find(c => "#" + c.id === location.hash);
    if (!cat) return false;
    select(cat, false);
    document.getElementById("laptops").scrollIntoView();
    return true;
  }
  window.addEventListener("hashchange", fromHash);
  if (fromHash()) {
    // the browser may restore the old scroll position; scroll again once everything loaded
    history.scrollRestoration = "manual";
    window.addEventListener("load", () => document.getElementById("laptops").scrollIntoView());
  }
}

render();
