// קטלוג המחשבים הניידים של BSD מחשבים.
// להוספה / עדכון מוצר: לערוך את הרשימה כאן. "price" ריק = "מחיר בוואטסאפ".
// specs: שורות המפרט שמוצגות בכרטיס. "windows": true אם המחשב מגיע עם Windows מהיצרן.
// also: קטגוריות נוספות שבהן המוצר יופיע (למשל ["recommended"]).
// soldOut: true = מוסתר זמנית מהקטלוג (חסר במלאי).
// page: עמוד מוצר נפרד (לחיצה על הכרטיס מובילה אליו). deal: תגית מבצע. price: מחיר בשקלים.
const CATEGORIES = [
  { id: "recommended", name: "מומלצים", desc: "הבחירות שלנו, במחירים מיוחדים" },
  { id: "deals", name: "🔥 מציאון", desc: "יחידות בודדות במחירי מציאה: חדשים באריזה וכמו חדשים" },
  { id: "refurbished", name: "מחודשים", desc: "מחשבים עסקיים מחודשים באיכות גבוהה, עם אחריות" },
  { id: "basic",    name: "בסיסי",        desc: "לגלישה, Office ולימודים" },
  { id: "home",     name: "ביתי ומשרדי",  desc: "עבודה יומיומית בנוחות" },
  { id: "business", name: "עסקי",         desc: "אמינות ואחריות לעסקים" },
  { id: "premium",  name: "פרימיום",      desc: "דקים, קלים ומסכי OLED" },
  { id: "gaming",   name: "גיימינג",      desc: "כרטיסי מסך RTX למשחקים ועריכה" },
  { id: "mac",      name: "מחשבי מקינטוש", desc: "MacBook של Apple" },
  { id: "desktop",  name: "מחשבים נייחים", desc: "מחשבים שולחניים לבית ולמשרד" },
  { id: "arch",     name: "אדריכלות ומולטימדיה", desc: "תחנות עבודה ניידות לתלת-ממד, תכנון ועריכת וידאו" },
  { id: "printers", name: "מדפסות", desc: "מדפסות לייזר, דיו ומשולבות לבית ולמשרד" },
  { id: "monitors", name: "מסכים", desc: "מסכי Dell ו-LG לבית, למשרד ולמקצוענים" },
];

const PRODUCTS = [
  { sku: "83K100W3IV", cat: "recommended", brand: "Lenovo", name: "Lenovo IdeaPad Slim 3 15 Touch i7",
    img: "images/83K100W3IV/2.avif", page: "laptop-ideapad-slim3-i7-touch.html",
    price: "3,350", deal: "מבצע לזמן מוגבל",
    tagline: "מסך מגע, גוף מתכת, i7 בהספק 45W ו-1TB",
    specs: ["מסך מגע 15.3 אינץ' WUXGA", "Intel Core i7-13620H (45W)", "16GB DDR5", "1TB SSD NVMe", "חלק עליון מאלומיניום", "אחריות שנה באתר הלקוח"] },

  { sku: "83K1-I7-512", cat: "home", also: ["recommended"], brand: "Lenovo", name: "Lenovo IdeaPad Slim 3 15 · i7-13620H · 512GB",
    img: "images/83K100W3IV/2.avif", page: "laptop-ideapad-slim3-i7-13620h-512gb.html", price: "3,090",
    tagline: "i7 בהספק 45W, גוף מתכת ומסך 15.3 אינץ' בהיר",
    specs: ["מסך 15.3 אינץ' WUXGA IPS", "Intel Core i7-13620H (45W)", "16GB DDR5", "512GB SSD NVMe", "חלק עליון מאלומיניום", "אחריות שנה באתר הלקוח"] },

  { sku: "X1605VA-MB2558", cat: "recommended", brand: "ASUS", name: "ASUS Vivobook 16 · Intel Core 9 270H",
    img: "images/x1605va-mb2558/main.jpg", page: "laptop-asus-vivobook16-core9-270h.html",
    deal: "מעבד Core 9", soldOut: true, // חסר זמנית במלאי: להחזיר price: "3,590" ולמחוק את soldOut
    tagline: "מעבד Core 9 דור חדש, ביצועים ברמת i9: ‏14 ליבות, עד 5.8GHz",
    specs: ["Intel Core 9 270H: ‏14 ליבות / 20 תהליכונים", "16GB DDR5 (אפשרות ל-24GB או 40GB)", "1TB SSD NVMe", "מסך 16 אינץ' WUXGA ‏16:10", "Windows 11 Pro", "אחריות יצרן לשנה"] },

  { sku: "83K100KPIV", cat: "home", also: ["recommended"], brand: "Lenovo", name: "Lenovo IdeaPad Slim 3 15 · i5-13420H · 16GB",
    img: "images/83K100W3IV/2.avif", page: "laptop-ideapad-slim3-i5-13420h-16gb.html", price: "2,690",
    tagline: "מסך IPS בהיר ומעבד i5 מהיר מסדרת H",
    specs: ["מסך 15.3 אינץ' IPS בהיר (300 ניטים)", "Intel Core i5-13420H, עד 4.6GHz", "16GB DDR5", "512GB SSD NVMe", "Windows 11 Home", "אחריות שנה באתר הלקוח"] },
  { sku: "83K1-I5-8GB", cat: "home", also: ["recommended"], brand: "Lenovo", name: "Lenovo IdeaPad Slim 3 15 · i5-13420H · 8GB",
    img: "images/83K100W3IV/2.avif", page: "laptop-ideapad-slim3-i5-13420h-8gb.html", price: "2,350",
    tagline: "מסך IPS בהיר ומעבד i5 מהיר, במחיר משתלם",
    specs: ["מסך 15.3 אינץ' IPS בהיר (300 ניטים)", "Intel Core i5-13420H, עד 4.6GHz", "8GB DDR5 (ניתן להרחבה)", "512GB SSD NVMe", "Windows 11 Home", "אחריות שנה באתר הלקוח"] },

  { sku: "TP14-R-8665U", cat: "refurbished", also: ["recommended"], brand: "Lenovo ThinkPad", name: "Lenovo ThinkPad T490 מחודש · i7 · מסך מגע",
    img: "images/thinkpad-refurb/tp-05.png", page: "laptop-thinkpad-refurbished-i7-touch.html",
    deal: "מחודש A-Grade", soldOut: true, // אזל זמנית מהמלאי: להחזיר price: "1,390" ולמחוק את soldOut
    tagline: "האגדה העסקית: אמין ועמיד לשנים, במחיר של מחשב בסיסי",
    specs: ["מסך מגע 14 אינץ' מט", "Intel Core i7-8665U", "8GB זיכרון (שדרוג ל-16GB)", "256GB SSD (שדרוג ל-512GB)", "עמידות צבאית MIL-STD-810G", "אחריות מלאה לחצי שנה"] },
  { sku: "TP14G1-R-I7-10", cat: "refurbished", brand: "Lenovo ThinkPad", name: "Lenovo ThinkPad T14 מחודש · i7 דור 10 · 16GB · מסך מגע",
    img: "images/thinkpad-refurb/tp-05.png", page: "laptop-thinkpad-t14-refurbished-i7-gen10.html",
    price: "1,650", deal: "יחידות בודדות במלאי",
    tagline: "ThinkPad עסקי עם מסך מגע ו-16GB זיכרון, אמין לשנים",
    specs: ["מסך מגע 14 אינץ'", "Intel Core i7 דור 10", "16GB זיכרון", "256GB SSD", "סוללה במצב מעולה", "אחריות מלאה לחצי שנה"] },

  { sku: "EB840-R-I7-8", cat: "refurbished", brand: "HP EliteBook", name: "HP EliteBook 840 מחודש · i7 דור 8 · מסך מגע",
    img: "images/elitebook-840/01.jpg", page: "laptop-hp-elitebook-840-refurbished-i7-touch.html", price: "1,390", deal: "מסך מגע",
    tagline: "מחשב עסקי באלומיניום, עם מסך מגע מט שלא נשבר",
    specs: ["מסך מגע 14 אינץ' מט · אפשר לכבות", "Intel Core i7 דור 8", "8GB זיכרון", "256GB SSD", "גוף אלומיניום · רשת RJ-45", "אחריות מלאה לחצי שנה"] },

  { sku: "82XB004UIV", cat: "basic", brand: "Lenovo", name: "Lenovo IdeaPad Slim 3 15 · i3-N305",
    img: "images/82xb004uiv/1.avif", page: "laptop-ideapad-slim3-15ian8-i3.html", price: "1,950",
    tagline: "מחשב חדש לגלישה, Office ולימודים, כולל התקנות",
    specs: ["מסך 15.6 אינץ' FHD", "Intel Core i3-N305 (8 ליבות)", "8GB זיכרון", "256GB SSD NVMe", "Wi-Fi 6", "אחריות שנה באתר הלקוח"] },
  { sku: "6092", cat: "basic", brand: "HP", name: "HP 250 G10", img: "images/6092.png",
    tagline: "הכי משתלם לגלישה ו-Office",
    specs: ["מסך 15.6 אינץ' FHD", "Intel Core 3 100U", "8GB זיכרון", "512GB SSD", "אחריות שנה"] },
  { sku: "6022", cat: "basic", brand: "ASUS", name: "ASUS Vivobook Go 14 · i3-N305",
    img: "images/e1404ga/01.jpg", page: "laptop-asus-vivobook-go14-i3-n305.html", price: "1,950",
    tagline: "קל ונייד: 1.38 ק\"ג, מושלם לתלמידים",
    specs: ["מסך 14 אינץ' Full HD", "Intel Core i3-N305: ‏8 ליבות", "8GB זיכרון", "512GB SSD", "NumberPad · עמידות צבאית", "אחריות שנה"] },
  { sku: "6044", cat: "basic", brand: "ASUS", name: "ASUS Vivobook 14 · i3-1315U",
    img: "images/x1404va/01.jpg", page: "laptop-asus-vivobook14-x1404va-i3-1315u.html", price: "2,090", deal: "ניתן לשדרוג",
    tagline: "דור 13, ניתן לשדרוג ל-16GB ו-1TB · כחול או כסוף",
    specs: ["מסך 14 אינץ' Full HD", "Intel Core i3-1315U (דור 13)", "8GB זיכרון (ניתן לשדרוג ל-16GB)", "512GB SSD (ניתן לשדרוג ל-1TB)", "Wi-Fi 6E · ‏1.4 ק\"ג", "אחריות שנה"] },
  { sku: "TP1401KA-EC170WS", cat: "basic", brand: "ASUS", name: "ASUS Vivobook Go 14 Flip · מתהפך",
    img: "images/vivobook-go14-flip/01.jpg", page: "laptop-asus-vivobook-go14-flip-tp1401ka.html", price: "1,990", deal: "מתהפך 360°",
    tagline: "נייד וטאבלט במכשיר אחד, עם מסך מגע",
    specs: ["מסך מגע 14 אינץ' Full HD", "מתהפך 360°: נייד, טאבלט, אוהל", "Intel Celeron N4500", "4GB · ‏128GB eMMC", "Windows 11 מקורית", "1.45 ק\"ג"] },
  { sku: "6294", cat: "basic", brand: "ASUS", name: "ASUS Vivobook 15", img: "images/6294.webp", windows: true,
    tagline: "מגיע עם Windows ו-3 שנות אחריות",
    specs: ["מסך 15.6 אינץ'", "Intel Core 5 120U", "8GB זיכרון", "512GB SSD", "Windows 11 Home", "אחריות 3 שנים"] },

  { sku: "6029", cat: "home", brand: "ASUS", name: "ASUS Vivobook 14", img: "images/6029.png",
    tagline: "מאוזן: 16GB ו-1TB במסך 14 אינץ'",
    specs: ["מסך 14 אינץ' FHD IPS", "Intel Core 5 120U", "16GB זיכרון", "1TB SSD", "אחריות שנה"] },
  { sku: "6338", cat: "home", brand: "Lenovo", name: "Lenovo IdeaPad Slim 3", img: "images/6338.webp",
    tagline: "הדור החדש ביותר בסדרה",
    specs: ["מסך 15.3 אינץ' IPS", "Intel Core 5 320", "16GB DDR5", "512GB SSD", "אחריות שנה"] },
  { sku: "6048", cat: "home", brand: "ASUS", name: "ASUS Vivobook 15 Touch", img: "images/6048.webp", windows: true,
    tagline: "מסך מגע, Windows ו-3 שנות אחריות",
    specs: ["מסך מגע 15.6 אינץ'", "Intel Core 7 150U", "16GB זיכרון", "1TB SSD", "Windows 11 Home", "אחריות 3 שנים"] },
  { sku: "6296", cat: "home", also: ["recommended"], brand: "ASUS", name: "ASUS Vivobook 15 · Ryzen 7 170 · 1TB",
    img: "images/m1502naq/1.webp", page: "laptop-asus-vivobook15-ryzen7-170.html", price: "2,790", deal: "הנחת מזומן",
    tagline: "מעבד ברמת i7 (לא i5) ו-1TB אחסון (לא 512GB)",
    specs: ["AMD Ryzen 7 170: ביצועים ברמת i7", "1TB SSD NVMe (לא 512GB)", "16GB DDR5", "מסך 15.6 אינץ' FHD IPS", "מקלדת מוארת", "אחריות שנה"] },
  { sku: "AL15-48P-R1RT", cat: "home", brand: "Acer", name: "Acer Aspire Lite 15 · Ryzen 7 · 16GB",
    img: "images/al15-48p/01.jpg", page: "laptop-acer-aspire-lite15-ryzen7-5825u-16gb.html", price: "2,390", deal: "שודרג ל-16GB",
    tagline: "Ryzen 7 עם 8 ליבות, זיכרון משודרג ל-16GB",
    specs: ["AMD Ryzen 7 5825U: ‏8 ליבות / 16 תהליכונים", "16GB DDR4 (שודרג, Dual Channel)", "512GB SSD NVMe", "מסך 15.6 אינץ' Full HD IPS", "Wi-Fi 6 · טעינה ב-USB-C", "אחריות שנה"] },
  { sku: "6128", cat: "home", brand: "ASUS", name: "ASUS Vivobook 17", img: "images/6128.png",
    tagline: "מסך ענק לעבודה מהבית",
    specs: ["מסך 17.3 אינץ'", "Intel Core 7 150U", "16GB זיכרון", "1TB SSD", "אחריות שנה"] },
  { sku: "6331", cat: "home", brand: "ASUS", name: "ASUS Vivobook 16", img: "images/6331.webp",
    tagline: "הכי חזק בלי כרטיס מסך נפרד",
    specs: ["מסך 16 אינץ' IPS", "Intel Core 9 270H", "24GB DDR5", "1TB SSD", "אחריות שנה"] },

  { sku: "PB4G1I-16-U5", cat: "business", also: ["recommended"], brand: "HP", name: "HP ProBook 4 G1i 16 · Core Ultra 5 · 4 שנות אחריות",
    img: "images/probook4-g1i-16/01.jpg", page: "laptop-hp-probook4-g1i-16-core-ultra5.html", price: "3,890", deal: "4 שנות אחריות",
    tagline: "מחשב עסקי עם מקלדת מוארת ו-4 שנות אחריות HP באתר הלקוח",
    specs: ["Intel Core Ultra 5 225U · מאיץ AI", "16GB DDR5 · ‏512GB SSD NVMe", "מסך 16 אינץ' WUXGA אנטי-בוהק", "מקלדת מוארת · קורא טביעת אצבע", "Windows 11 Pro מקורית", "4 שנות אחריות HP באתר הלקוח"] },
  { sku: "PC14255-R5-512", cat: "business", brand: "Dell", name: "Dell Pro 14 · Ryzen 5 · 16GB · 512GB",
    img: "images/deals/dell-pro14/01.jpg", page: "laptop-dell-pro14-pc14255-ryzen5.html",
    price: "2,690", was: "4,500", deal: "מבצע", stockLow: true,
    tagline: "מחשב עסקי חדש במחיר של מחשב ביתי",
    specs: ["AMD Ryzen 5 220: ‏6 ליבות", "16GB DDR5 (עד 64GB)", "512GB SSD NVMe", "מסך 14 אינץ' FHD+ ‏16:10", "רשת RJ-45 · ‏Wi-Fi 6E · ‏1.36 ק\"ג", "אחריות יצרן מלאה"] },
  { sku: "E14G6-R5-512", cat: "business", brand: "Lenovo ThinkPad", name: "Lenovo ThinkPad E14 Gen 6 · Ryzen 5 · 16GB",
    img: "images/deals/e14-gen6/01.jpg", page: "laptop-thinkpad-e14-gen6-ryzen5-7535u.html", price: "2,690",
    tagline: "ThinkPad חדש: מקלדת מעולה, עמידות צבאית ושדרוג עד 64GB",
    specs: ["AMD Ryzen 5 7535U: ‏6 ליבות", "16GB DDR5 (עד 64GB)", "512GB SSD + חריץ פנוי", "מסך 14 אינץ' ‏16:10", "מקלדת עמידה לשפיכה · ‏MIL-STD-810H", "אחריות יצרן מלאה"] },
  { sku: "E14G7-R5-16-512", cat: "business", brand: "Lenovo ThinkPad", name: "Lenovo ThinkPad E14 Gen 7 · Ryzen 5 · 16GB",
    img: "images/deals/e14-gen7/01.jpg", page: "laptop-thinkpad-e14-gen7-ryzen5-230-16gb.html", price: "2,990", deal: "AI PC",
    tagline: "הדור החדש של ThinkPad, עם מעבד AI ויציאת USB4",
    specs: ["AMD Ryzen 5 230 · מעבד AI", "16GB DDR5 (עד 64GB)", "512GB SSD + חריץ פנוי", "מסך 14 אינץ' WUXGA ‏16:10", "USB4 · רשת RJ-45 · ‏MIL-STD-810H", "אחריות יצרן מלאה"] },
  { sku: "6028", cat: "business", brand: "HP", name: "HP 250R G9", img: "images/6028.webp",
    tagline: "עסקי במחיר נוח, אחריות באתר הלקוח",
    specs: ["מסך 15.6 אינץ' FHD", "Intel Core 7 150U", "16GB זיכרון", "512GB SSD", "קורא טביעת אצבע", "אחריות 3 שנים באתר"] },
  { sku: "6113", cat: "business", brand: "ASUS", name: "ASUS ExpertBook P1", img: "images/6113.webp",
    tagline: "סדרה עסקית עם אחריות באתר",
    specs: ["מסך 14 אינץ' FHD", "Intel Core 5 210H", "16GB זיכרון", "512GB SSD", "אחריות שנה באתר"] },
  { sku: "6245", cat: "business", brand: "Lenovo", name: "Lenovo ThinkPad E14 Gen 7", img: "images/6245.avif",
    tagline: "ThinkPad: עמיד, עם מקלדת מעולה",
    specs: ["מסך 14 אינץ'", "Intel Core Ultra 7 255H", "16GB זיכרון", "512GB SSD", "אחריות 3 שנים"] },
  { sku: "6335", cat: "business", brand: "ASUS", name: "ASUS ExpertBook B3", img: "images/6335.webp", windows: true,
    tagline: "סים 4G מובנה, לאנשי שטח",
    specs: ["מסך מגע 14 אינץ'", "Intel Core Ultra 5 225H", "16GB זיכרון", "512GB SSD", "4G LTE מובנה", "Windows 11 Pro", "אחריות 3 שנים באתר"] },
  { sku: "LAT7455-X1P", cat: "business", also: ["premium"], brand: "Dell", name: "Dell Latitude 7455 · Snapdragon X Plus",
    img: "images/latitude7455/01.jpg", page: "laptop-dell-latitude-7455-snapdragon-x-plus.html", price: "3,890", deal: "Copilot+ PC",
    tagline: "נייד עסקי יוקרתי מאלומיניום, סוללה ליום עבודה מלא",
    specs: ["מסך מגע 14 אינץ' QHD+ ‏400 ניט", "Snapdragon X Plus: ‏10 ליבות", "16GB LPDDR5x", "512GB SSD", "1.44 ק\"ג · Wi-Fi 7", "Windows 11 Pro · אחריות שנה"] },

  { sku: "UM3406GA-QD010", cat: "premium", also: ["recommended"], brand: "ASUS", name: "ASUS Zenbook 14 OLED · Ryzen AI 7 · 1TB",
    img: "images/zenbook14-um3406ga/01.jpg", page: "laptop-asus-zenbook14-oled-ryzen-ai7-445.html", price: "3,890", deal: "מבצע במזומן",
    tagline: "OLED, ‏1.2 ק\"ג ואלומיניום מלא, כולל Windows 11 Pro",
    specs: ["AMD Ryzen AI 7 445 · ‏NPU ‏50 TOPS", "16GB LPDDR5X · ‏1TB SSD", "מסך OLED ‏14 אינץ' ‏100% DCI-P3", "1.2 ק\"ג · אלומיניום · תקן צבאי", "Wi-Fi 6E · ‏USB4 · ‏HDMI 2.1", "Windows 11 Pro מקורי"] },
  { sku: "6098", cat: "premium", brand: "ASUS", name: "ASUS Zenbook 14 OLED", img: "images/6098.png",
    tagline: "דק, קל ומסך OLED מרהיב",
    specs: ["מסך 14 אינץ' 3K OLED", "Intel Core Ultra 5 225H", "16GB זיכרון", "1TB SSD", "אחריות שנה באתר"] },
  { sku: "6089", cat: "premium", brand: "Lenovo", name: "Lenovo IdeaPad 2in1 14", img: "images/6089.png",
    tagline: "נייד וטאבלט במכשיר אחד",
    specs: ["מסך מגע מתהפך 14 אינץ'", "Intel Core Ultra 7 255H", "16GB זיכרון", "512GB SSD", "אחריות 3 שנים"] },
  { sku: "6300", cat: "premium", brand: "Lenovo", name: "Lenovo IdeaPad 5 2in1 OLED", img: "images/6300.png",
    tagline: "2in1 ברמה הגבוהה ביותר",
    specs: ["מסך מגע 14 אינץ' OLED", "Intel Core Ultra 7 255H", "24GB זיכרון", "512GB SSD", "אחריות 3 שנים"] },

  { sku: "6318", cat: "gaming", brand: "Lenovo", name: "Lenovo LOQ 15", img: "images/6318.webp",
    tagline: "הכניסה לעולם הגיימינג",
    specs: ["מסך 15.6 אינץ'", "Intel Core i7-13650HX", "16GB זיכרון", "1TB SSD", "RTX 3050 6GB", "אחריות שנה"] },
  { sku: "6320", cat: "arch", also: ["gaming"], brand: "ASUS", name: "ASUS TUF Gaming A16 · Ryzen 9 · RTX 5060",
    img: "images/fa608pm/01.webp", page: "laptop-asus-tuf-a16-ryzen9-8940hx-rtx5060.html", price: "6,590", deal: "Ryzen 9",
    tagline: "תחנת עבודה ניידת לאדריכלות, תלת-ממד ועריכת וידאו",
    specs: ["AMD Ryzen 9 8940HX: ‏16 ליבות / 32 תהליכונים", "RTX 5060 8GB", "32GB DDR5", "1TB SSD NVMe", "מסך 16 אינץ' IPS ‏165Hz", "סוללה 90Wh · אחריות 3 שנים"] },
  { sku: "6079", cat: "arch", also: ["gaming"], brand: "Lenovo", name: "Lenovo LOQ 15 · i7-14700HX · RTX 5060",
    img: "images/loq15irx10/01.jpg", page: "laptop-lenovo-loq15-i7-14700hx-rtx5060.html", price: "6,390", deal: "הנחת מזומן",
    tagline: "תחנת עבודה ניידת לאדריכלות, גרפיקה ותלת-ממד",
    specs: ["Intel Core i7-14700HX: ‏20 ליבות / 28 תהליכונים", "RTX 5060 8GB GDDR7", "32GB DDR5", "1TB SSD NVMe", "מסך 15.6 אינץ' IPS ‏144Hz ‏100% sRGB", "Windows 11 Pro · אחריות 3 שנים"] },
  { sku: "6236", cat: "gaming", brand: "ASUS", name: "ASUS TUF Gaming A16", img: "images/6236.webp",
    tagline: "גיימינג חזק עם 3 שנות אחריות",
    specs: ["מסך 16 אינץ'", "AMD Ryzen 9 8940HX", "16GB זיכרון", "1TB SSD", "RTX 5060 8GB", "אחריות 3 שנים"] },
  { sku: "6332", cat: "gaming", brand: "Lenovo", name: "Lenovo Legion 5 16", img: "images/6332.webp",
    tagline: "דגל הגיימינג",
    specs: ["מסך 16 אינץ'", "AMD Ryzen 9 8940HX", "32GB DDR5", "1TB SSD", "RTX 5070 8GB", "אחריות 3 שנים"] },
  { sku: "83LT0065IV", cat: "gaming", also: ["arch"], brand: "Lenovo", name: "Lenovo Legion Pro 5 16 · Ryzen 9 · RTX 5070",
    img: "images/legion-pro5/01.jpg", page: "laptop-lenovo-legion-pro5-ryzen9-rtx5070.html", price: "7,890", deal: "RTX 5070",
    tagline: "מסך ⁦2560×1600⁩ ‏240Hz ‏500 ניט, ביצועים בלי פשרות",
    specs: ["מסך 16 אינץ' ⁦2560×1600⁩ ‏IPS ‏240Hz", "AMD Ryzen 9 8940HX: ‏16 ליבות", "RTX 5070 8GB GDDR7", "32GB DDR5", "1TB SSD + חריץ פנוי", "סוללה 80Wh · אחריות 3 שנים"] },

  { sku: "MBA15-M3-24-512", cat: "mac", brand: "Apple", name: "MacBook Air 15 · M3 · 24GB · 512GB",
    img: "images/macbook-air-15-m3/01.jpg", page: "laptop-macbook-air-15-m3-24gb-512gb.html", price: "4,490", deal: "כמעט חדש", stockLow: true,
    zap: { price: "7,648", label: "MacBook Air 15 חדש עם 24GB ו-512GB (דור M4)" },
    tagline: "מצב מעולה, כמעט חדש: דק, שקט ועם סוללה ליום שלם",
    specs: ["Apple M3: ‏8 ליבות מעבד, 10 ליבות גרפיקה", "24GB זיכרון · ‏512GB SSD", "מסך 15.3 אינץ' Liquid Retina", "עד 18 שעות סוללה · ללא מאוורר", "1.51 ק\"ג · ‏Touch ID", "אחריות BSD לחצי שנה"] },

  { sku: "MBP16-M1MAX-32-1TB", cat: "mac", brand: "Apple", name: "MacBook Pro 16 · M1 Max · 32GB · 1TB",
    img: "images/macbook-pro-16-m1max/01.jpg", page: "laptop-macbook-pro-16-m1-max-32gb-1tb.html", price: "3,600", deal: "M1 Max", stockLow: true,
    zap: { price: "10,837", label: "MacBook Pro 16 חדש (הדגם הבסיסי, M5 Pro)" },
    tagline: "תחנת עבודה ניידת מקצועית, במחיר של מחשב בסיסי",
    specs: ["Apple M1 Max: ‏10 ליבות מעבד", "32GB זיכרון · ‏1TB SSD", "מסך 16.2 אינץ' Liquid Retina XDR ‏120Hz", "HDMI, קורא SD ו-3 × Thunderbolt 4", "עד 21 שעות סוללה", "אחריות BSD לחצי שנה"] },
  { sku: "MBP16-I9-32-1TB", cat: "mac", brand: "Apple", name: "MacBook Pro 16 · Intel i9 · 32GB · 1TB",
    img: "images/macbook-pro-16-intel/01.jpg", page: "laptop-macbook-pro-16-intel-i9-32gb-1tb.html", price: "2,900", deal: "מריץ גם Windows", stockLow: true,
    tagline: "הדור האחרון עם Intel: אפשר להתקין גם Windows",
    specs: ["Intel Core i9 דור 9: ‏8 ליבות", "32GB זיכרון · ‏1TB SSD", "כרטיס מסך AMD Radeon Pro", "מסך 16 אינץ' Retina", "Touch Bar · ‏4 × Thunderbolt 3", "אחריות BSD לחצי שנה"] },
  { sku: "M70QG5-14500T", cat: "desktop", also: ["recommended"], brand: "Lenovo ThinkCentre", name: "Lenovo ThinkCentre M70q Tiny Gen 5",
    img: "images/m70q-gen5/m70q-01.jpg", page: "desktop-lenovo-m70q-gen5-i5-14500t.html", price: "2,790", deal: "מעבד שולחני",
    tagline: "מעבד שולחני אמיתי, לא מעבד נייד, בגוף זעיר",
    specs: ["Intel Core i5-14500T (שולחני): ‏14 ליבות", "16GB DDR5", "512GB SSD NVMe + חריץ פנוי", "Windows 11 Pro מקורית", "כולל תושבת VESA לגב המסך", "אחריות 3 שנים באתר הלקוח"] },
  { sku: "PM400G9-16-512", cat: "desktop", also: ["recommended"], brand: "HP", name: "HP Pro Mini 400 G9 · 16GB · 512GB",
    img: "images/hp-pro-mini-400-g9/2.png", page: "desktop-hp-pro-mini-400-g9-16gb-512gb.html", price: "2,590",
    tagline: "מחשב מיני עסקי חזק, תופס מקום של ספר",
    specs: ["Intel Core i5-12500T (6 ליבות)", "16GB DDR4", "512GB SSD NVMe", "רשת קווית Gigabit", "עד 3 מסכים (HDMI + 2×DP)"] },
  { sku: "BSD-SET-PM400-LG24", cat: "desktop", also: ["recommended"], brand: "BSD מחשבים", name: "מערכת מחשב מושלמת · HP Pro Mini + מסך LG 24 + מקלדת ועכבר",
    img: "images/set-hp-mini-lg24/01.jpg", page: "desktop-set-hp-mini-lg24-keyboard-mouse.html", price: "3,050", deal: "כולל מסך",
    tagline: "מחשב, מסך, מקלדת ועכבר: הכל מוכן לעבודה",
    specs: ["HP Pro Mini 400 G9 · ‏Intel Core i5-12500T", "16GB DDR4 · ‏512GB SSD NVMe", "מסך LG ‏24 אינץ' IPS ‏120Hz", "סט מקלדת ועכבר אלחוטיים", "רשת קווית Gigabit"] },
  { sku: "PM400G9-8-256", cat: "desktop", also: ["recommended"], brand: "HP", name: "HP Pro Mini 400 G9 · 8GB · 256GB",
    img: "images/hp-pro-mini-400-g9/2.png", page: "desktop-hp-pro-mini-400-g9-8gb-256gb.html", price: "1,890",
    tagline: "מחשב מיני עסקי במחיר משתלם",
    specs: ["Intel Core i5-12500T (6 ליבות)", "8GB DDR4", "256GB SSD NVMe", "רשת קווית Gigabit", "עד 3 מסכים (HDMI + 2×DP)"] },
  { sku: "CG4H5EA", cat: "desktop", also: ["arch"], brand: "HP", name: "HP OmniDesk AI · Core Ultra 7 265 · RTX 5060",
    img: "images/omnidesk/01.jpg", page: "desktop-hp-omnidesk-ultra7-265-rtx5060.html", price: "6,990", deal: "20 ליבות",
    tagline: "מחשב שולחני חזק עם Windows 11 Pro, מקלדת ועכבר",
    specs: ["Intel Core Ultra 7 265: ‏20 ליבות", "RTX 5060 8GB", "32GB DDR5", "1TB SSD NVMe", "Windows 11 Pro + מקלדת ועכבר", "אחריות 3 שנים באתר הלקוח"] },
  { sku: "6020-1", cat: "desktop", also: ["gaming"], brand: "ASUS", name: "ASUS TUF Gaming T500MV · RTX 5060 · 1TB",
    img: "images/tuf-t500/01.jpg", page: "desktop-asus-tuf-t500mv-core7-rtx5060.html", price: "6,990", deal: "RTX 5060",
    tagline: "מחשב גיימינג נייח עם פאנל זכוכית ו-RGB",
    specs: ["Intel Core 7 240H", "RTX 5060 8GB", "32GB DDR5 (עד 64GB)", "1TB SSD NVMe", "עד 4 מסכים · תקן צבאי", "אחריות יצרן 3 שנים"] },
  { sku: "BSD-KIT-U7-5060", cat: "desktop", also: ["gaming", "recommended"], brand: "BSD מחשבים", name: "ערכת מחשב מלאה · Core Ultra 7 · RTX 5060 + מסך Dell 24",
    img: "images/pc-kit/01.jpg", page: "desktop-kit-ultra7-265kf-rtx5060-dell24.html", price: "8,450", deal: "כולל מסך",
    tagline: "מחשב, מסך, מקלדת ועכבר: הכל מוכן לעבודה",
    specs: ["Intel Core Ultra 7 265KF: ‏20 ליבות", "RTX 5060 8GB", "32GB DDR5-5600", "2TB SSD סמסונג (⁦2×1TB⁩)", "מסך Dell 24 אינץ' IPS מתכוונן", "סט אלחוטי Lenovo · ספק 850W"] },

  // ---------- מדפסות ----------
  { sku: "5530", cat: "printers", brand: "Brother", name: "Brother HL-L2445DW", img: "images/printers/5530.jpg",
    tagline: "מדפסת לייזר שחור-לבן אלחוטית",
    specs: ["לייזר שחור-לבן", "הדפסה דו-צדדית אוטומטית", "Wi-Fi + USB"] },
  { sku: "6258", cat: "printers", brand: "Brother", name: "Brother HL-L1240W", img: "images/printers/6258.jpg",
    tagline: "מדפסת לייזר קומפקטית אלחוטית",
    specs: ["לייזר שחור-לבן", "קומפקטית", "Wi-Fi + USB"] },
  { sku: "452", cat: "printers", brand: "Brother", name: "Brother HL-1210W", img: "images/printers/452.jpg",
    tagline: "מדפסת לייזר קטנה לבית",
    specs: ["לייזר שחור-לבן", "קומפקטית", "Wi-Fi + USB"] },
  { sku: "5416", cat: "printers", brand: "Brother", name: "Brother MFC-L2800DW", img: "images/printers/5416.jpg",
    tagline: "משולבת לייזר: הדפסה, צילום, סריקה ופקס",
    specs: ["לייזר שחור-לבן", "הדפסה · צילום · סריקה · פקס", "הדפסה דו-צדדית אוטומטית", "Wi-Fi + USB"] },
  { sku: "6259", cat: "printers", brand: "Brother", name: "Brother DCP-L1660W", img: "images/printers/6259.jpg",
    tagline: "משולבת לייזר: הדפסה, צילום וסריקה",
    specs: ["לייזר שחור-לבן", "הדפסה · צילום · סריקה", "Wi-Fi + USB"] },
  { sku: "5418", cat: "printers", brand: "Brother", name: "Brother MFC-L5710DW", img: "images/printers/5418.jpg",
    tagline: "משולבת לייזר עסקית",
    specs: ["לייזר שחור-לבן", "הדפסה · צילום · סריקה · פקס", "הדפסה דו-צדדית אוטומטית", "Wi-Fi + רשת"] },
  { sku: "6215", cat: "printers", brand: "Brother", name: "Brother HL-L5210DN", img: "images/printers/6215.jpg",
    tagline: "מדפסת לייזר עסקית לרשת",
    specs: ["לייזר שחור-לבן", "הדפסה דו-צדדית אוטומטית", "רשת (RJ-45) + USB"] },
  { sku: "5928", cat: "printers", brand: "Brother", name: "Brother HL-L6410DN", img: "images/printers/5928.jpg",
    tagline: "מדפסת לייזר עסקית לעומסים גבוהים",
    specs: ["לייזר שחור-לבן", "הדפסה דו-צדדית אוטומטית", "רשת (RJ-45) + USB"] },
  { sku: "1648", cat: "printers", brand: "Brother", name: "Brother HL-L8260CDW", img: "images/printers/1648.jpg",
    tagline: "מדפסת לייזר צבעונית",
    specs: ["לייזר צבעוני", "הדפסה דו-צדדית אוטומטית", "Wi-Fi + רשת"] },
  { sku: "5420", cat: "printers", brand: "Brother", name: "Brother MFC-L3740CDW", img: "images/printers/5420.jpg",
    tagline: "משולבת לייזר צבעונית",
    specs: ["לייזר צבעוני", "הדפסה · צילום · סריקה · פקס", "הדפסה דו-צדדית אוטומטית", "Wi-Fi + רשת"] },
  { sku: "5603", cat: "printers", brand: "Brother", name: "Brother MFC-L3760CDW", img: "images/printers/5603.jpg",
    tagline: "משולבת לייזר צבעונית",
    specs: ["לייזר צבעוני", "הדפסה · צילום · סריקה · פקס", "הדפסה דו-צדדית אוטומטית", "Wi-Fi + רשת"] },
  { sku: "1431", cat: "printers", brand: "Brother", name: "Brother MFC-L8690CDW", img: "images/printers/1431.jpg",
    tagline: "משולבת לייזר צבעונית עסקית",
    specs: ["לייזר צבעוני", "הדפסה · צילום · סריקה · פקס", "הדפסה דו-צדדית אוטומטית", "Wi-Fi + רשת"] },
  { sku: "6096", cat: "printers", brand: "Brother", name: "Brother DCP-J1360DW", img: "images/printers/6096.jpg",
    tagline: "משולבת דיו צבעונית לבית",
    specs: ["דיו צבעוני", "הדפסה · צילום · סריקה", "הדפסה דו-צדדית אוטומטית", "Wi-Fi + USB"] },
  { sku: "6097", cat: "printers", brand: "Brother", name: "Brother MFC-J4350DW", img: "images/printers/6097.jpg",
    tagline: "משולבת דיו צבעונית עם פקס",
    specs: ["דיו צבעוני", "הדפסה · צילום · סריקה · פקס", "הדפסה דו-צדדית אוטומטית", "Wi-Fi + USB"] },
  { sku: "1601", cat: "printers", brand: "Brother", name: "Brother MFC-J5330DW A3", img: "images/printers/1601.jpg",
    tagline: "משולבת דיו צבעונית עם הדפסת A3",
    specs: ["דיו צבעוני · הדפסה עד A3", "הדפסה · צילום · סריקה · פקס", "הדפסה דו-צדדית אוטומטית", "Wi-Fi + רשת"] },
  { sku: "2876", cat: "printers", brand: "Brother", name: "Brother MFC-J5340DW A3", img: "images/printers/2876.jpg",
    tagline: "משולבת דיו צבעונית עם הדפסת A3",
    specs: ["דיו צבעוני · הדפסה עד A3", "הדפסה · צילום · סריקה · פקס", "הדפסה דו-צדדית אוטומטית", "Wi-Fi + רשת"] },
  { sku: "6214", cat: "printers", brand: "Brother", name: "Brother MFC-J6760DW A3", img: "images/printers/6214.jpg",
    tagline: "משולבת דיו A3 עם 2 מגשי נייר",
    specs: ["דיו צבעוני · A3", "הדפסה · צילום · סריקה · פקס", "הדפסה דו-צדדית אוטומטית", "Wi-Fi + רשת"] },
  { sku: "6288", cat: "printers", brand: "Epson", name: "Epson EcoTank L3350", img: "images/printers/6288.jpg",
    tagline: "משולבת עם מכלי דיו למילוי חוזר",
    specs: ["מכלי דיו (EcoTank)", "הדפסה · צילום · סריקה", "Wi-Fi", "אחריות שנה"] },
  { sku: "6289", cat: "printers", brand: "Epson", name: "Epson EcoTank L3360", img: "images/printers/6289.jpg",
    tagline: "משולבת עם מכלי דיו למילוי חוזר",
    specs: ["מכלי דיו (EcoTank)", "הדפסה · צילום · סריקה", "Wi-Fi", "אחריות שנה"] },
  { sku: "6290", cat: "printers", brand: "Epson", name: "Epson EcoTank L6276", img: "images/printers/6290.jpg",
    tagline: "משולבת מכלי דיו עם מזין מסמכים",
    specs: ["מכלי דיו (EcoTank)", "הדפסה · צילום · סריקה", "מזין מסמכים אוטומטי (ADF)", "Wi-Fi · אחריות שנה"] },
  { sku: "5126", cat: "printers", brand: "Pantum", name: "Pantum P3300DW", img: "images/printers/5126.jpg",
    tagline: "מדפסת לייזר אלחוטית לרשת",
    specs: ["לייזר שחור-לבן", "הדפסה דו-צדדית אוטומטית", "Wi-Fi + רשת + USB"] },
  { sku: "5127-2", cat: "printers", brand: "Pantum", name: "Pantum M7100DW + זוג טונרים", img: "images/printers/5127-2.jpg", deal: "כולל 2 טונרים",
    tagline: "משולבת לייזר, כולל זוג טונרים מקוריים",
    specs: ["לייזר שחור-לבן", "הדפסה · צילום · סריקה", "הדפסה דו-צדדית אוטומטית", "Wi-Fi · כולל 2 טונרים מקוריים"] },

  // ---------- מסכים ----------
  { sku: "SE2425HM", cat: "monitors", brand: "Dell", name: "Dell 24 SE2425HM", img: "images/monitors/se2425hm/01.jpg",
    page: "monitor-dell-se2425hm-24-ips-100hz.html", price: "319", deal: "הכי משתלם",
    tagline: "מסך 24 אינץ' IPS ‏100Hz במחיר נמוך",
    specs: ["23.8 אינץ' Full HD ‏IPS", "100Hz", "ComfortView Plus", "HDMI + VGA"] },
  { sku: "24U411A-B", cat: "monitors", brand: "LG", name: "LG 24U411A-B", img: "images/monitors/lg24u411a/01.jpg",
    page: "monitor-lg-24u411a-24-ips-120hz.html", price: "365", deal: "120Hz",
    tagline: "24 אינץ' IPS ‏120Hz עם 99% sRGB",
    specs: ["23.8 אינץ' Full HD ‏IPS", "120Hz · ‏1ms MBR", "99% sRGB · ‏HDR10", "HDMI + VGA"] },
  { sku: "E2425HSM", cat: "monitors", brand: "Dell", name: "Dell Pro 24 E2425HSM", img: "images/monitors/e2425hsm/01.jpg",
    page: "monitor-dell-pro-e2425hsm-24-adjustable.html", price: "389",
    tagline: "מתכוונן לגובה, עם רמקולים מובנים",
    specs: ["23.8 אינץ' Full HD ‏IPS ‏100Hz", "מעמד מתכוונן לגובה + Pivot", "רמקולים מובנים", "HDMI · DP · VGA"] },
  { sku: "P2425H", cat: "monitors", brand: "Dell", name: "Dell Pro 24 Plus P2425H", img: "images/monitors/p2425h/01.jpg",
    page: "monitor-dell-pro-p2425h-24-usb-hub.html", price: "490",
    tagline: "מסך מקצועי: 99% sRGB ורכזת USB",
    specs: ["23.8 אינץ' Full HD ‏IPS ‏100Hz", "99% sRGB · ניגודיות 1,500:1", "רכזת USB עם USB-C", "מעמד מתכוונן 15 ס\"מ"] },
  { sku: "S2725QC", cat: "monitors", brand: "Dell", name: "Dell 27 Plus 4K S2725QC", img: "images/monitors/s2725qc/01.jpg",
    page: "monitor-dell-27-plus-4k-s2725qc-usb-c.html", price: "1,199", deal: "4K",
    tagline: "27 אינץ' 4K ‏120Hz עם USB-C",
    specs: ["27 אינץ' 4K UHD ‏IPS", "120Hz · ‏99% sRGB", "USB-C עם טעינה 65W", "רמקולים ⁦2×5W⁩ · מעמד מתכוונן"] },
  { sku: "P3424WEB", cat: "monitors", brand: "Dell", name: "Dell Pro 34 Curved P3424WEB", img: "images/monitors/p3424web/01.jpg",
    page: "monitor-dell-pro-34-curved-p3424web-webcam.html", price: "2,070", deal: "קעור 34",
    tagline: "34 אינץ' קעור עם מצלמה לשיחות וידאו",
    specs: ["34 אינץ' קעור WQHD ‏⁦3440×1440⁩", "מצלמה 2K + מיקרופונים", "USB-C עם טעינה 90W", "רשת מובנית · KVM"] },
];
