// קטלוג המחשבים הניידים של BSD מחשבים.
// להוספה / עדכון מוצר: לערוך את הרשימה כאן. "price" ריק = "מחיר בוואטסאפ".
// specs: שורות המפרט שמוצגות בכרטיס. "windows": true אם המחשב מגיע עם Windows מהיצרן.
// also: קטגוריות נוספות שבהן המוצר יופיע (למשל ["recommended"]).
// page: עמוד מוצר נפרד (לחיצה על הכרטיס מובילה אליו). deal: תגית מבצע. price: מחיר בשקלים.
const CATEGORIES = [
  { id: "recommended", name: "מומלצים", desc: "הבחירות שלנו, במחירים מיוחדים" },
  { id: "refurbished", name: "מחודשים", desc: "מחשבים עסקיים מחודשים באיכות גבוהה, עם אחריות" },
  { id: "basic",    name: "בסיסי",        desc: "לגלישה, Office ולימודים" },
  { id: "home",     name: "ביתי ומשרדי",  desc: "עבודה יומיומית בנוחות" },
  { id: "business", name: "עסקי",         desc: "אמינות ואחריות לעסקים" },
  { id: "premium",  name: "פרימיום",      desc: "דקים, קלים ומסכי OLED" },
  { id: "gaming",   name: "גיימינג",      desc: "כרטיסי מסך RTX למשחקים ועריכה" },
  { id: "desktop",  name: "מחשבים נייחים", desc: "מחשבים שולחניים לבית ולמשרד" },
  { id: "arch",     name: "אדריכלות ומולטימדיה", desc: "תחנות עבודה ניידות לתלת-ממד, תכנון ועריכת וידאו" },
];

const PRODUCTS = [
  { sku: "83K100W3IV", cat: "recommended", brand: "Lenovo", name: "Lenovo IdeaPad Slim 3 15 Touch i7",
    img: "images/83K100W3IV/2.avif", page: "laptop-ideapad-slim3-i7-touch.html",
    price: "3,249", deal: "מבצע לזמן מוגבל",
    tagline: "מסך מגע, גוף מתכת, i7 בהספק 45W ו-1TB",
    specs: ["מסך מגע 15.3 אינץ' WUXGA", "Intel Core i7-13620H (45W)", "16GB DDR5", "1TB SSD NVMe", "חלק עליון מאלומיניום", "אחריות שנה באתר הלקוח"] },

  { sku: "X1605VA-MB2558", cat: "recommended", brand: "ASUS", name: "ASUS Vivobook 16 · Intel Core 9 270H",
    img: "images/x1605va-mb2558/main.jpg", page: "laptop-asus-vivobook16-core9-270h.html",
    price: "3,590", deal: "מעבד Core 9",
    tagline: "מעבד Core 9 דור חדש, ביצועים ברמת i9: ‏14 ליבות, עד 5.8GHz",
    specs: ["Intel Core 9 270H: ‏14 ליבות / 20 תהליכונים", "16GB DDR5 (אפשרות ל-24GB או 40GB)", "1TB SSD NVMe", "מסך 16 אינץ' WUXGA ‏16:10", "Windows 11 Pro", "אחריות יצרן לשנה"] },

  { sku: "83K100KPIV", cat: "home", also: ["recommended"], brand: "Lenovo", name: "Lenovo IdeaPad Slim 3 15 · i5-13420H · 16GB",
    img: "images/83K100W3IV/2.avif", page: "laptop-ideapad-slim3-i5-13420h-16gb.html", price: "2,690",
    tagline: "מסך IPS בהיר ומעבד i5 מהיר מסדרת H",
    specs: ["מסך 15.3 אינץ' IPS בהיר (300 ניטים)", "Intel Core i5-13420H, עד 4.6GHz", "16GB DDR5", "512GB SSD NVMe", "Windows 11 Home", "אחריות שנה באתר הלקוח"] },
  { sku: "83K1-I5-8GB", cat: "home", also: ["recommended"], brand: "Lenovo", name: "Lenovo IdeaPad Slim 3 15 · i5-13420H · 8GB",
    img: "images/83K100W3IV/2.avif", page: "laptop-ideapad-slim3-i5-13420h-8gb.html", price: "2,350",
    tagline: "מסך IPS בהיר ומעבד i5 מהיר, במחיר משתלם",
    specs: ["מסך 15.3 אינץ' IPS בהיר (300 ניטים)", "Intel Core i5-13420H, עד 4.6GHz", "8GB DDR5 (ניתן להרחבה)", "512GB SSD NVMe", "Windows 11 Home", "אחריות שנה באתר הלקוח"] },

  { sku: "TP14-R-8665U", cat: "refurbished", also: ["recommended"], brand: "Lenovo ThinkPad", name: "Lenovo ThinkPad T490 מחודש · i7 · מסך מגע",
    img: "images/thinkpad-refurb/tp-05.png", page: "laptop-thinkpad-refurbished-i7-touch.html",
    price: "1,390", deal: "מחודש A-Grade",
    tagline: "האגדה העסקית: אמין ועמיד לשנים, במחיר של מחשב בסיסי",
    specs: ["מסך מגע 14 אינץ' מט", "Intel Core i7-8665U", "8GB זיכרון (שדרוג ל-16GB)", "256GB SSD (שדרוג ל-512GB)", "עמידות צבאית MIL-STD-810G", "אחריות מלאה לחצי שנה"] },

  { sku: "82XB004UIV", cat: "basic", brand: "Lenovo", name: "Lenovo IdeaPad Slim 3 15 · i3-N305",
    img: "images/82xb004uiv/1.avif", page: "laptop-ideapad-slim3-15ian8-i3.html", price: "1,950",
    tagline: "מחשב חדש לגלישה, Office ולימודים, כולל התקנות",
    specs: ["מסך 15.6 אינץ' FHD", "Intel Core i3-N305 (8 ליבות)", "8GB זיכרון", "256GB SSD NVMe", "Wi-Fi 6", "אחריות שנה באתר הלקוח"] },
  { sku: "6092", cat: "basic", brand: "HP", name: "HP 250 G10", img: "images/6092.png",
    tagline: "הכי משתלם לגלישה ו-Office",
    specs: ["מסך 15.6 אינץ' FHD", "Intel Core 3 100U", "8GB זיכרון", "512GB SSD", "אחריות שנה"] },
  { sku: "6022", cat: "basic", brand: "ASUS", name: "ASUS Vivobook Go 14", img: "images/6022.png",
    tagline: "קל וקומפקטי, מושלם לתלמידים",
    specs: ["מסך 14 אינץ'", "Intel Core i3-N305", "8GB זיכרון", "512GB SSD", "אחריות שנה"] },
  { sku: "6294", cat: "basic", brand: "ASUS", name: "ASUS Vivobook 15", img: "images/6294.webp", windows: true,
    tagline: "מגיע עם Windows ו-3 שנות אחריות",
    specs: ["מסך 15.6 אינץ'", "Intel Core 5 120U", "8GB זיכרון", "512GB SSD", "Windows 11 Home", "אחריות 3 שנים"] },

  { sku: "6029", cat: "home", brand: "ASUS", name: "ASUS Vivobook 14", img: "images/6029.png",
    tagline: "מאוזן: 16GB ו-1TB במסך 14 אינץ'",
    specs: ["מסך 14 אינץ' FHD IPS", "Intel Core 5 120U", "16GB זיכרון", "1TB SSD", "אחריות שנה"] },
  { sku: "6338", cat: "home", brand: "Lenovo", name: "Lenovo IdeaPad Slim 3", img: "images/6338.webp",
    tagline: "הדור החדש ביותר בסדרה",
    specs: ["מסך 15.3 אינץ' IPS", "Intel Core 5 320", "16GB DDR5", "512GB SSD", "אחריות שנה"] },
  { sku: "6048", cat: "home", brand: "ASUS", name: "ASUS Vivobook 15 Touch", img: "images/6048.webp", windows: true,
    tagline: "מסך מגע, Windows ו-3 שנות אחריות",
    specs: ["מסך מגע 15.6 אינץ'", "Intel Core 7 150U", "16GB זיכרון", "1TB SSD", "Windows 11 Home", "אחריות 3 שנים"] },
  { sku: "6296", cat: "home", also: ["recommended"], brand: "ASUS", name: "ASUS Vivobook 15 · Ryzen 7 170 · 1TB",
    img: "images/m1502naq/1.webp", page: "laptop-asus-vivobook15-ryzen7-170.html", price: "2,790", deal: "1TB אחסון",
    tagline: "Ryzen 7 עם 8 ליבות מלאות ו-1TB אחסון",
    specs: ["AMD Ryzen 7 170: ‏8 ליבות / 16 תהליכונים", "1TB SSD NVMe", "16GB DDR5", "מסך 15.6 אינץ' FHD IPS", "מקלדת מוארת", "אחריות שנה"] },
  { sku: "6128", cat: "home", brand: "ASUS", name: "ASUS Vivobook 17", img: "images/6128.png",
    tagline: "מסך ענק לעבודה מהבית",
    specs: ["מסך 17.3 אינץ'", "Intel Core 7 150U", "16GB זיכרון", "1TB SSD", "אחריות שנה"] },
  { sku: "6331", cat: "home", brand: "ASUS", name: "ASUS Vivobook 16", img: "images/6331.webp",
    tagline: "הכי חזק בלי כרטיס מסך נפרד",
    specs: ["מסך 16 אינץ' IPS", "Intel Core 9 270H", "24GB DDR5", "1TB SSD", "אחריות שנה"] },

  { sku: "6028", cat: "business", brand: "HP", name: "HP 250R G9", img: "images/6028.webp",
    tagline: "עסקי במחיר נוח, אחריות באתר הלקוח",
    specs: ["מסך 15.6 אינץ' FHD", "Intel Core 7 150U", "16GB זיכרון", "512GB SSD", "קורא טביעת אצבע", "אחריות 3 שנים באתר"] },
  { sku: "6113", cat: "business", brand: "ASUS", name: "ASUS ExpertBook P1", img: "images/6113.webp",
    tagline: "סדרה עסקית עם אחריות באתר",
    specs: ["מסך 14 אינץ' FHD", "Intel Core 5 210H", "16GB זיכרון", "512GB SSD", "אחריות שנה באתר"] },
  { sku: "6245", cat: "business", brand: "Lenovo", name: "Lenovo ThinkPad E14 Gen 7", img: "images/6245.avif",
    tagline: "ThinkPad: עמיד, עם מקלדת מעולה",
    specs: ["מסך 14 אינץ'", "Intel Core Ultra 7 255H", "16GB זיכרון", "512GB SSD", "אחריות 3 שנים"] },
  { sku: "6335", cat: "business", brand: "ASUS", name: "ASUS ExpertBook B3", img: "images/6335.webp", windows: true,
    tagline: "סים 4G מובנה, לאנשי שטח",
    specs: ["מסך מגע 14 אינץ'", "Intel Core Ultra 5 225H", "16GB זיכרון", "512GB SSD", "4G LTE מובנה", "Windows 11 Pro", "אחריות 3 שנים באתר"] },

  { sku: "6098", cat: "premium", brand: "ASUS", name: "ASUS Zenbook 14 OLED", img: "images/6098.png",
    tagline: "דק, קל ומסך OLED מרהיב",
    specs: ["מסך 14 אינץ' 3K OLED", "Intel Core Ultra 5 225H", "16GB זיכרון", "1TB SSD", "אחריות שנה באתר"] },
  { sku: "6089", cat: "premium", brand: "Lenovo", name: "Lenovo IdeaPad 2in1 14", img: "images/6089.png",
    tagline: "נייד וטאבלט במכשיר אחד",
    specs: ["מסך מגע מתהפך 14 אינץ'", "Intel Core Ultra 7 255H", "16GB זיכרון", "512GB SSD", "אחריות 3 שנים"] },
  { sku: "6300", cat: "premium", brand: "Lenovo", name: "Lenovo IdeaPad 5 2in1 OLED", img: "images/6300.png",
    tagline: "2in1 ברמה הגבוהה ביותר",
    specs: ["מסך מגע 14 אינץ' OLED", "Intel Core Ultra 7 255H", "24GB זיכרון", "512GB SSD", "אחריות 3 שנים"] },

  { sku: "6318", cat: "gaming", brand: "Lenovo", name: "Lenovo LOQ 15", img: "images/6318.webp",
    tagline: "הכניסה לעולם הגיימינג",
    specs: ["מסך 15.6 אינץ'", "Intel Core i7-13650HX", "16GB זיכרון", "1TB SSD", "RTX 3050 6GB", "אחריות שנה"] },
  { sku: "6320", cat: "arch", also: ["gaming"], brand: "ASUS", name: "ASUS TUF Gaming A16 · Ryzen 9 · RTX 5060",
    img: "images/fa608pm/01.webp", page: "laptop-asus-tuf-a16-ryzen9-8940hx-rtx5060.html", price: "6,590", deal: "Ryzen 9",
    tagline: "תחנת עבודה ניידת לאדריכלות, תלת-ממד ועריכת וידאו",
    specs: ["AMD Ryzen 9 8940HX: ‏16 ליבות / 32 תהליכונים", "RTX 5060 8GB", "32GB DDR5", "1TB SSD NVMe", "מסך 16 אינץ' IPS ‏165Hz", "סוללה 90Wh · אחריות 3 שנים"] },
  { sku: "6079", cat: "arch", also: ["gaming"], brand: "Lenovo", name: "Lenovo LOQ 15 · i7-14700HX · RTX 5060",
    img: "images/loq15irx10/01.jpg", page: "laptop-lenovo-loq15-i7-14700hx-rtx5060.html", price: "6,390", deal: "הנחת מזומן",
    tagline: "תחנת עבודה ניידת לאדריכלות, גרפיקה ותלת-ממד",
    specs: ["Intel Core i7-14700HX: ‏20 ליבות / 28 תהליכונים", "RTX 5060 8GB GDDR7", "32GB DDR5", "1TB SSD NVMe", "מסך 15.6 אינץ' IPS ‏144Hz ‏100% sRGB", "Windows 11 Pro · אחריות 3 שנים"] },
  { sku: "6236", cat: "gaming", brand: "ASUS", name: "ASUS TUF Gaming A16", img: "images/6236.webp",
    tagline: "גיימינג חזק עם 3 שנות אחריות",
    specs: ["מסך 16 אינץ'", "AMD Ryzen 9 8940HX", "16GB זיכרון", "1TB SSD", "RTX 5060 8GB", "אחריות 3 שנים"] },
  { sku: "6332", cat: "gaming", brand: "Lenovo", name: "Lenovo Legion 5 16", img: "images/6332.webp",
    tagline: "דגל הגיימינג",
    specs: ["מסך 16 אינץ'", "AMD Ryzen 9 8940HX", "32GB DDR5", "1TB SSD", "RTX 5070 8GB", "אחריות 3 שנים"] },

  { sku: "M70QG5-14500T", cat: "desktop", also: ["recommended"], brand: "Lenovo ThinkCentre", name: "Lenovo ThinkCentre M70q Tiny Gen 5",
    img: "images/m70q-gen5/m70q-01.jpg", page: "desktop-lenovo-m70q-gen5-i5-14500t.html", price: "2,790", deal: "מעבד שולחני",
    tagline: "מעבד שולחני אמיתי, לא מעבד נייד, בגוף זעיר",
    specs: ["Intel Core i5-14500T (שולחני): ‏14 ליבות", "16GB DDR5", "512GB SSD NVMe + חריץ פנוי", "Windows 11 Pro מקורית", "כולל תושבת VESA לגב המסך", "אחריות 3 שנים באתר הלקוח"] },
  { sku: "PM400G9-16-512", cat: "desktop", also: ["recommended"], brand: "HP", name: "HP Pro Mini 400 G9 · 16GB · 512GB",
    img: "images/hp-pro-mini-400-g9/2.png", page: "desktop-hp-pro-mini-400-g9-16gb-512gb.html", price: "2,590",
    tagline: "מחשב מיני עסקי חזק, תופס מקום של ספר",
    specs: ["Intel Core i5-12500T (6 ליבות)", "16GB DDR4", "512GB SSD NVMe", "רשת קווית Gigabit", "עד 3 מסכים (HDMI + 2×DP)"] },
  { sku: "PM400G9-8-256", cat: "desktop", also: ["recommended"], brand: "HP", name: "HP Pro Mini 400 G9 · 8GB · 256GB",
    img: "images/hp-pro-mini-400-g9/2.png", page: "desktop-hp-pro-mini-400-g9-8gb-256gb.html", price: "1,890",
    tagline: "מחשב מיני עסקי במחיר משתלם",
    specs: ["Intel Core i5-12500T (6 ליבות)", "8GB DDR4", "256GB SSD NVMe", "רשת קווית Gigabit", "עד 3 מסכים (HDMI + 2×DP)"] },
];
